version: "2.4"

services:
  daemon:
    image: bluefunny/mcsm-daemon:latest
    volumes:
      # This is the MCSManager web panel log storage directory
      # Default is [/var/logs/mcsmanager/daemon]
      - /var/logs/mcsmanager/daemon:/logs

      # This is the MCSManager daemon data storage directory
      # Default is the data/daemon folder in the current directory
      - ./data/daemon:/data
    network_mode: host
    command: /start
